apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-13T16:25:49Z"
  labels:
    run: nginx-resolver
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-08-13T16:25:49Z"
  name: nginx-resolver
  namespace: default
  resourceVersion: "9793"
  selfLink: /api/v1/namespaces/default/services/nginx-resolver
  uid: a23ed0e5-6086-446b-b990-413fcc407096
spec:
  clusterIP: 10.105.206.1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-resolver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
