apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-resolver
  name: nginx-resolver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
  type: ClusterIP
status:
  loadBalancer: {}
