apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx-dev
        image: nginx:1.16.1
        ports:
        - containerPort: 80
